version: '3'

services:
  shared_mysql:
    container_name: ivanhernandez-ferreteria_hernandez-mysql
    image: mysql:8
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    entrypoint:
      sh -c "
      echo 'CREATE DATABASE IF NOT EXISTS inventory; CREATE DATABASE IF NOT EXISTS catalog;' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
    command: [ "--default-authentication-plugin=mysql_native_password" ]

  shared_rabbitmq:
    container_name: ivanhernandez-ferreteria_hernandez-rabbitmq
    image: 'rabbitmq:3.7-management'
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "5630:5672"
      - "8090:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=ivanhernandez
      - RABBITMQ_DEFAULT_PASS=iV4nH3rn4Nd3Z

  inventory_backend_server_java:
    container_name: ivanhernandez-ferreteria_hernandez-inventory_backend_server
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8020:8020"
    volumes:
      - .:/app:delegated
      - inventory_backend_gradle_cache:/app/.gradle
    depends_on:
      - shared_mysql
      - shared_rabbitmq
    command: [ "./gradlew", "bootRun", "--args", "inventory_backend server" ]

  catalog_backend_server_java:
    container_name: ivanhernandez-ferreteria_hernandez-catalog_backend_server
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8010:8010"
    volumes:
      - .:/app:delegated
      - catalog_backend_gradle_cache:/app/.gradle
    depends_on:
      - shared_mysql
      - shared_rabbitmq
    command: [ "./gradlew", "bootRun", "--args", "catalog_backend server" ]

  test_server_java:
    container_name: ivanhernandez-ferreteria_hernandez-test_server
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app:delegated
      - test_gradle_cache:/app/.gradle
    depends_on:
      - shared_mysql
      - shared_rabbitmq
      - inventory_backend_server_java
      - catalog_backend_server_java
    tty: true

volumes:
  test_gradle_cache:
  inventory_backend_gradle_cache:
  catalog_backend_gradle_cache:
